; [env:esp32s3]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino

; lib_deps =
;     thomasfredericks/Bounce2 @ ^2.71
;     gin66/FastAccelStepper

; monitor_speed = 115200
; upload_protocol = esptool
; upload_port = /dev/cu.usbmodem*
; upload_speed = 921600


[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    thomasfredericks/Bounce2 @ ^2.71
    gin66/FastAccelStepper

# Exclude individual state files from direct compilation since they're included via StateMachine_Functions.cpp
build_src_filter = 
    +<*>
    -<StateMachine/STATES/*.cpp>
    -<StateMachine/STATES/cut_cycle/*.cpp>

monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.1.228
